In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder

In [2]:
df_train = pd.read_csv(r"D:\DataSet AAI\train.csv")
df_test = pd.read_csv(r"D:\DataSet AAI\test.csv")

print(df_train.head())

   Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0           0   70172    Male     Loyal Customer   13  Personal Travel
1           1    5047    Male  disloyal Customer   25  Business travel
2           2  110028  Female     Loyal Customer   26  Business travel
3           3   24026  Female     Loyal Customer   25  Business travel
4           4  119299    Male     Loyal Customer   61  Business travel

      Class  Flight Distance  Inflight wifi service  \
0  Eco Plus              460                      3
1  Business              235                      3
2  Business             1142                      2
3  Business              562                      2
4  Business              214                      3

   Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                  4  ...                       5
1                                  2  ...                       1
2                                  2  ...                       5
3                                  5  ...                       2
4                                  3  ...                       3

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4
1                 1                 5                 3                1
2                 4                 3                 4                4
3                 2                 5                 3                1
4                 3                 4                 4                3

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25
1                 4            1                           1
2                 4            5                           0
3                 4            2                          11
4                 3            3                           0

   Arrival Delay in Minutes             satisfaction
0                      18.0  neutral or dissatisfied
1                       6.0  neutral or dissatisfied
2                       0.0                satisfied
3                       9.0  neutral or dissatisfied
4                       0.0                satisfied

[5 rows x 25 columns]

In [3]:
df_train.drop(columns=["Unnamed: 0", "id"], inplace=True)

In [4]:
#drop missing values
df_train.dropna(inplace=True)

In [5]:
# Check for null values
print(df_train.isnull().sum())

Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [6]:
print(df_train.head())

   Gender      Customer Type  Age   Type of Travel     Class  Flight Distance  \
0    Male     Loyal Customer   13  Personal Travel  Eco Plus              460
1    Male  disloyal Customer   25  Business travel  Business              235
2  Female     Loyal Customer   26  Business travel  Business             1142
3  Female     Loyal Customer   25  Business travel  Business              562
4    Male     Loyal Customer   61  Business travel  Business              214

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4
1                      3                                  2
2                      2                                  2
3                      2                                  5
4                      3                                  3

   Ease of Online booking  Gate location  ...  Inflight entertainment  \
0                       3              1  ...                       5
1                       3              3  ...                       1
2                       2              2  ...                       5
3                       5              5  ...                       2
4                       3              3  ...                       3

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4
1                 1                 5                 3                1
2                 4                 3                 4                4
3                 2                 5                 3                1
4                 3                 4                 4                3

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25
1                 4            1                           1
2                 4            5                           0
3                 4            2                          11
4                 3            3                           0

   Arrival Delay in Minutes             satisfaction
0                      18.0  neutral or dissatisfied
1                       6.0  neutral or dissatisfied
2                       0.0                satisfied
3                       9.0  neutral or dissatisfied
4                       0.0                satisfied

[5 rows x 23 columns]

Encode the categorical variables

In [7]:
# List of columns to encode
label_cols = ['Gender', 'Customer Type', 'Type of Travel', 'Class','satisfaction']

# Encode each column
for col in label_cols:
    le = LabelEncoder()
    df_train[col] = le.fit_transform(df_train[col])
    

print(df_train.head(5))

   Gender  Customer Type  Age  Type of Travel  Class  Flight Distance  \
0       1              0   13               1      2              460
1       1              1   25               0      0              235
2       0              0   26               0      0             1142
3       0              0   25               0      0              562
4       1              0   61               0      0              214

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4
1                      3                                  2
2                      2                                  2
3                      2                                  5
4                      3                                  3

   Ease of Online booking  Gate location  ...  Inflight entertainment  \
0                       3              1  ...                       5
1                       3              3  ...                       1
2                       2              2  ...                       5
3                       5              5  ...                       2
4                       3              3  ...                       3

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4
1                 1                 5                 3                1
2                 4                 3                 4                4
3                 2                 5                 3                1
4                 3                 4                 4                3

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25
1                 4            1                           1
2                 4            5                           0
3                 4            2                          11
4                 3            3                           0

   Arrival Delay in Minutes  satisfaction
0                      18.0             0
1                       6.0             0
2                       0.0             1
3                       9.0             0
4                       0.0             1

[5 rows x 23 columns]

In [8]:
#encode the target column
target_encoder = LabelEncoder()
df_train['satisfaction'] = target_encoder.fit_transform(df_train['satisfaction'])

In [9]:
print(df_train.head(5))

   Gender  Customer Type  Age  Type of Travel  Class  Flight Distance  \
0       1              0   13               1      2              460
1       1              1   25               0      0              235
2       0              0   26               0      0             1142
3       0              0   25               0      0              562
4       1              0   61               0      0              214

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4
1                      3                                  2
2                      2                                  2
3                      2                                  5
4                      3                                  3

   Ease of Online booking  Gate location  ...  Inflight entertainment  \
0                       3              1  ...                       5
1                       3              3  ...                       1
2                       2              2  ...                       5
3                       5              5  ...                       2
4                       3              3  ...                       3

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4
1                 1                 5                 3                1
2                 4                 3                 4                4
3                 2                 5                 3                1
4                 3                 4                 4                3

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25
1                 4            1                           1
2                 4            5                           0
3                 4            2                          11
4                 3            3                           0

   Arrival Delay in Minutes  satisfaction
0                      18.0             0
1                       6.0             0
2                       0.0             1
3                       9.0             0
4                       0.0             1

[5 rows x 23 columns]

In [10]:
# Generate synthetic complaint text

def generate_complaint(row):
    complaint = []
    if row['Inflight wifi service'] <= 2:
        complaint.append("wifi was slow and unstable.")
    if row['Food and drink'] <= 2:
        complaint.append("The food and drink were poor.")
    if row['Departure/Arrival time convenient'] <= 2:
        complaint.append("Departure and arrival time were very inconvienient.")
    if row['Ease of Online booking'] <= 2:
        complaint.append("Online booking was difficult.")
    if row['Seat comfort'] <= 2:
        complaint.append("Seat was uncomfortable.")
    if row['Gate location'] <= 2:
        complaint.append("gate location was confusing.")
    if row['Inflight entertainment'] <= 2:
        complaint.append("inflight entertaintment was poor.")
    if row['On-board service'] <= 2:
        complaint.append("Onboard service felt unhelpful.")
    if row["Leg room service"] <= 2:
        complaint.append("Legroom was insufficient.")
    if row['Baggage handling'] <= 2:
        complaint.append("Baggage handling was unsatisfactory.")
    if row['Checkin service'] <= 2:
        complaint.append("Check-in service was poor.")
    if row['Inflight service'] <= 2:
        complaint.append("Inflight service was below expectation.")
    if row['Cleanliness'] <= 2:
        complaint.append("The plane was not clean.")
    return " and ".join(complaint) if complaint else "No complaint"

df_train['Complaint_Text'] = df_train.apply(generate_complaint, axis=1)

In [11]:
# generate synthetic positive feedback
def generate_positive_feedback(row):
    feedback = []
    if row['Inflight wifi service'] >= 3:
        feedback.append("WiFi was fast and stable.")
    if row['Food and drink'] >= 4:
        feedback.append("The food and drink were delicious.")
    if row['Departure/Arrival time convenient'] >= 4:
        feedback.append("Departure and arrival time were very accurate.")
    if row['Ease of Online booking'] >= 3:
        feedback.append("Online booking was smooth.")
    if row['Seat comfort'] >= 3:
        feedback.append("Seats were very comfortable.")
    if row['Gate location'] >= 4:
        feedback.append("gate location was helpful.")
    if row['Inflight entertainment'] >= 3:
        feedback.append("Excellent inflight entertainment options.")
    if row['On-board service'] >= 3:
        feedback.append("The onboard service was excellent.")
    if row["Leg room service"] >= 3:
        feedback.append("Legroom was sufficient.")
    if row['Baggage handling'] >= 3:
        feedback.append("Baggage handling was satisfactory.")
    if row['Checkin service'] >= 4:
        feedback.append("Check-in process was smooth and quick.")
    if row['Inflight service'] >= 3:
        feedback.append("Inflight service was amazing.")
    if row['Cleanliness'] >= 4:
        feedback.append("The cabin was clean and well maintained.")
    return " ".join(feedback) if feedback else "No feedback"

df_train['Positive_Feedback'] = df_train.apply(generate_positive_feedback,axis=1)

In [12]:
df_train["Feedback_Text"] = df_train.apply(
    lambda row: row["Complaint_Text"] if row["satisfaction"] == 0 else row["Positive_Feedback"],
    axis=1
)

In [13]:
print(df_train.columns)

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction', 'Complaint_Text', 'Positive_Feedback', 'Feedback_Text'],
      dtype='object')

Text Preprocessing

In [14]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [15]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = re.sub(r"[^a-zA-Z]", " ", text.lower())
    words = text.split()
    cleaned = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return " ".join(cleaned)

df_train["Cleaned_Text"] = df_train["Complaint_Text"].apply(clean_text)
print(df_train["Cleaned_Text"])

0                                   gate location confusing
1         food drink poor departure arrival time inconvi...
2         wifi slow unstable departure arrival time inco...
3         wifi slow unstable food drink poor seat uncomf...
4                                                 complaint
                                ...
103899    wifi slow unstable food drink poor departure a...
103900                                      food drink poor
103901    wifi slow unstable departure arrival time inco...
103902    wifi slow unstable food drink poor departure a...
103903    wifi slow unstable food drink poor seat uncomf...
Name: Cleaned_Text, Length: 103594, dtype: object

Word Embedding

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_text = tfidf.fit_transform(df_train["Cleaned_Text"])

In [17]:
# Get feature (word) names
feature_names = tfidf.get_feature_names_out()

# Choose how many documents to print
num_docs_to_print = 5  # You can increase this

for i in range(num_docs_to_print):
    print(f"\n--- Document {i+1} ---")
    print("Cleaned Text:", df_train["Cleaned_Text"].iloc[i])

    # Get the tf-idf vector for document i
    row = X_text[i]

    # Convert it to a dense format and zip with feature names
    scores = zip(feature_names, row.toarray()[0])

    # Filter non-zero scores and sort by importance
    sorted_scores = sorted([(word, score) for word, score in scores if score > 0], key=lambda x: -x[1])

    print("TF-IDF Scores:")
    for word, score in sorted_scores:
        print(f"{word}: {score:.4f}")

--- Document 1 ---
Cleaned Text: gate location confusing
TF-IDF Scores:
confusing: 0.5774
gate: 0.5774
location: 0.5774

--- Document 2 ---
Cleaned Text: food drink poor departure arrival time inconvienient seat uncomfortable inflight entertaintment poor onboard service felt unhelpful check service poor plane clean
TF-IDF Scores:
poor: 0.4562
service: 0.3435
check: 0.2228
felt: 0.2201
onboard: 0.2201
unhelpful: 0.2201
seat: 0.2187
uncomfortable: 0.2187
clean: 0.2104
plane: 0.2104
entertaintment: 0.2083
drink: 0.1946
food: 0.1946
inflight: 0.1898
arrival: 0.1867
departure: 0.1867
inconvienient: 0.1867
time: 0.1867

--- Document 3 ---
Cleaned Text: wifi slow unstable departure arrival time inconvienient online booking difficult gate location confusing
TF-IDF Scores:
confusing: 0.2931
gate: 0.2931
location: 0.2931
arrival: 0.2894
departure: 0.2894
inconvienient: 0.2894
time: 0.2894
booking: 0.2617
difficult: 0.2617
online: 0.2617
slow: 0.2594
unstable: 0.2594
wifi: 0.2594

--- Document 4 ---
Cleaned Text: wifi slow unstable food drink poor seat uncomfortable inflight entertaintment poor onboard service felt unhelpful check service poor plane clean
TF-IDF Scores:
poor: 0.4694
service: 0.3535
check: 0.2293
felt: 0.2265
onboard: 0.2265
unhelpful: 0.2265
seat: 0.2250
uncomfortable: 0.2250
clean: 0.2165
plane: 0.2165
entertaintment: 0.2144
drink: 0.2002
food: 0.2002
inflight: 0.1953
slow: 0.1722
unstable: 0.1722
wifi: 0.1722

--- Document 5 ---
Cleaned Text: complaint
TF-IDF Scores:
complaint: 1.0000

Transformer based model

In [18]:
#fine tuning DistilBERT
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
import torch

# Create a dataset
df_small = df_train.sample(n=10000, random_state=42).reset_index(drop=True)

df_nlp = df_small[['Cleaned_Text', 'satisfaction']].rename(columns={'Cleaned_Text': 'text', 'satisfaction': 'label'})

#convert pandas dataframe into Hugging face dataset
dataset = Dataset.from_pandas(df_nlp)

#Split the dataset into train and test
dataset = dataset.train_test_split(test_size=0.2)

In [19]:
# Tokenize the text (DistilBERT can't read raw text it needs tokenized inputs(word embedding))
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/8000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [20]:
#Load the pre trained DistilBERT for classification
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [21]:
# Train the BERT model
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    num_train_epochs=10,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01,
    gradient_accumulation_steps=4,
    load_best_model_at_end=True,
    logging_dir="./logs",
    dataloader_pin_memory=False,
)

In [23]:
%pip install evaluate

Requirement already satisfied: evaluate in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (0.4.5)
Requirement already satisfied: datasets>=2.0.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (2.13.1)
Requirement already satisfied: numpy>=1.17 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (0.3.6)
Requirement already satisfied: pandas in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (2.3.2)
Requirement already satisfied: requests>=2.19.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (0.70.14)
Requirement already satisfied: fsspec>=2021.05.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (0.34.4)
Requirement already satisfied: packaging in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from evaluate) (25.0)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from datasets>=2.0.0->evaluate) (12.0.1)
Requirement already satisfied: aiohttp in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from datasets>=2.0.0->evaluate) (3.12.15)
Requirement already satisfied: pyyaml>=5.1 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: filelock in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (3.19.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.1)
Requirement already satisfied: idna>=2.0 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets>=2.0.0->evaluate) (3.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from requests>=2.19.0->evaluate) (2.1.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from requests>=2.19.0->evaluate) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from requests>=2.19.0->evaluate) (2022.12.7)
Requirement already satisfied: colorama in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\miniconda3\envs\aai_gpu_env\lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
#evaluate the model performance during training and testing
import evaluate

#load accuracy metric from hugging face evaluate library
metric = evaluate.load("accuracy")

def compute_metric(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions,references=labels)

Using the latest cached version of the module from C:\Users\ASUS\.cache\huggingface\modules\evaluate_modules\metrics\evaluate-metric--accuracy\f887c0aab52c2d38e1f8a215681126379eca617f96c447638f751434e8e65b14 (last modified on Mon Sep  1 18:11:45 2025) since it couldn't be found locally at evaluate-metric--accuracy, or remotely on the Hugging Face Hub.

In [ ]:

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    compute_metrics=compute_metric,
)

trainer.train()

TrainOutput(global_step=5000, training_loss=0.4473273071289062, metrics={'train_runtime': 18843.5954, 'train_samples_per_second': 4.245, 'train_steps_per_second': 0.265, 'total_flos': 2649347973120000.0, 'train_loss': 0.4473273071289062, 'epoch': 10.0})

In [ ]:
trainer.evaluate()

{'eval_loss': 0.453392893075943,
 'eval_accuracy': 0.802,
 'eval_runtime': 73.3739,
 'eval_samples_per_second': 27.258,
 'eval_steps_per_second': 6.814,
 'epoch': 10.0}

In [ ]:
df_train["satisfaction"].value_counts(normalize=True)

satisfaction
0    0.566606
1    0.433394
Name: proportion, dtype: float64

In [25]:
# Detect device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)  # Move model to the correct device

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
# Save the models

trainer.save_model("./saved_distilbert_model")
tokenizer.save_pretrained("./saved_distilbert_model")

('./saved_distilbert_model\\tokenizer_config.json',
 './saved_distilbert_model\\special_tokens_map.json',
 './saved_distilbert_model\\vocab.txt',
 './saved_distilbert_model\\added_tokens.json')

In [23]:
# To reload the saved model

from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
model = DistilBertForSequenceClassification.from_pretrained("./saved_distilbert_model")
tokenizer = DistilBertTokenizer.from_pretrained("./saved_distilbert_model")

In [24]:
# Custom examples to test model behavior
test_texts = [
    "The seat was very uncomfortable and the food was terrible.",
    "Everything was excellent, the flight was smooth and the staff were great.",
    "WiFi was bad and boarding took too long.",
    "Very friendly staff and excellent inflight entertainment.",
    "Seat was very comfortable and has very great inflight experience"
]

# Tokenize
inputs = tokenizer(test_texts, return_tensors="pt", padding=True, truncation=True)

label_map  = {
    0:"dissatisfied or neutral",
    1:"satisfied"
}
# Predict
model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    predictions = torch.argmax(outputs.logits, dim=-1)

# Decode label
predicted_labels = [label_map[pred.item()] for pred in predictions]

for text, label in zip(test_texts, predicted_labels):
    print(f"\nText: {text}\nPredicted: {label}")

Text: The seat was very uncomfortable and the food was terrible.
Predicted: dissatisfied or neutral

Text: Everything was excellent, the flight was smooth and the staff were great.
Predicted: dissatisfied or neutral

Text: WiFi was bad and boarding took too long.
Predicted: dissatisfied or neutral

Text: Very friendly staff and excellent inflight entertainment.
Predicted: satisfied

Text: Seat was very comfortable and has very great inflight experience
Predicted: dissatisfied or neutral

In [25]:
from collections import Counter
print(Counter(tokenized_datasets["train"]["label"]))

Counter({0: 4533, 1: 3467})

Integrate Generative AI Component (Autoencoder)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from keras.models import Sequential
from keras.layers import Dense

# Convert Cleaned_Text to TF-IDF
vectorizer = TfidfVectorizer(max_features=1000)
X_text = vectorizer.fit_transform(df_train["Cleaned_Text"])

# Autoencoder model
autoencoder = Sequential([
    Dense(128, activation='relu', input_shape=(X_text.shape[1],)),
    Dense(64, activation='relu'),
    Dense(128, activation='relu'),
    Dense(X_text.shape[1], activation='sigmoid')
])

autoencoder.compile(optimizer='adam', loss='binary_crossentropy')
autoencoder.fit(X_text.toarray(), X_text.toarray(), epochs=25, batch_size=64)

c:\Users\ASUS\miniconda3\envs\aai_gpu_env\lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.1976
Epoch 2/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.1796
Epoch 3/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.1794
Epoch 4/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1794
Epoch 5/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1793
Epoch 6/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1793
Epoch 7/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1793
Epoch 8/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 9/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 10/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.1792
Epoch 11/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 12/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 13/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 14/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.1792
Epoch 15/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 16/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 17/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 18/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 19/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 20/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 21/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 22/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 23/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792
Epoch 24/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1791
Epoch 25/25
1619/1619 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.1792

Few Shots training with DistilBERT

In [29]:
#Create a few shot subset
df_few = df_train.sample(n=200, random_state=42).reset_index(drop=True)

# Keep only the text and label columns
df_few_nlp = df_few[['Cleaned_Text', 'satisfaction']].rename(columns={'Cleaned_Text': 'text', 'satisfaction': 'label'})

In [30]:
#Convert to hugging face dataset and split
from datasets import Dataset

dataset_few = Dataset.from_pandas(df_few_nlp)
dataset_few = dataset_few.train_test_split(test_size=0.2)

In [31]:
#Tokenize the dataset
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_few = dataset_few.map(tokenize_function, batched=True)

Map:   0%|          | 0/160 [00:00<?, ? examples/s]

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

In [32]:
#Load pre trained DistilBERT model
from transformers import DistilBertForSequenceClassification

few_model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [33]:
#Define the training arguments
from transformers import TrainingArguments, Trainer

training_args_few = TrainingArguments(
    output_dir="./few_shot_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    num_train_epochs=20,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    logging_dir="./few_shot_logs",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

In [34]:
#Define trainer and train
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}

In [ ]:
trainer_few = Trainer(
    model=few_model,
    args=training_args_few,
    train_dataset=tokenized_few["train"],
    eval_dataset=tokenized_few["test"],
    compute_metrics=compute_metrics,
)

trainer_few.train()

c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=400, training_loss=0.4034219700098038, metrics={'train_runtime': 628.6985, 'train_samples_per_second': 5.09, 'train_steps_per_second': 0.636, 'total_flos': 105973918924800.0, 'train_loss': 0.4034219700098038, 'epoch': 20.0})

In [ ]:
#evaluate
metrics = trainer_few.evaluate()
print(metrics)

c:\Advanced-AI-project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'eval_loss': 0.3267073631286621, 'eval_accuracy': 0.925, 'eval_f1': 0.8888888888888888, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_runtime': 1.4362, 'eval_samples_per_second': 27.852, 'eval_steps_per_second': 3.481, 'epoch': 20.0}

In [ ]:
#save few shots model
few_model.save_pretrained("fewshot-distilbert-satisfaction")
tokenizer.save_pretrained("fewshot-distilbert-satisfaction")

('fewshot-distilbert-satisfaction\\tokenizer_config.json',
 'fewshot-distilbert-satisfaction\\special_tokens_map.json',
 'fewshot-distilbert-satisfaction\\vocab.txt',
 'fewshot-distilbert-satisfaction\\added_tokens.json')

In [35]:
# reload the saved few shot model
from transformers import DistilBertForSequenceClassification

few_model = DistilBertForSequenceClassification.from_pretrained("./fewshot-distilbert-satisfaction")
tokenizer = DistilBertTokenizer.from_pretrained("./fewshot-distilbert-satisfaction")

Prompt Engineering

In [36]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

text = "The food was cold and the seat was very cramped."
labels = ["satisfied", "dissatisfied or neutral"]

result = classifier(text, candidate_labels=labels)

print(result)

config.json: 0.00B [00:00, ?B/s]

c:\Users\ASUS\miniconda3\envs\aai_gpu_env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub\models--facebook--bart-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

{'sequence': 'The food was cold and the seat was very cramped.', 'labels': ['dissatisfied or neutral', 'satisfied'], 'scores': [0.961159348487854, 0.03884069621562958]}

In [37]:
from transformers import pipeline

# Use a public, instruction-tuned model
classifier = pipeline("text2text-generation", model="google/flan-t5-base")

prompt = """
You are an airline sentiment classifier.
Classify the feedback as either "satisfied" or "dissatisfied or neutral".

Examples:
Feedback: Everything was smooth and the service was great.
Label: satisfied

Feedback: The flight was delayed and the crew was rude.
Label: dissatisfied or neutral

Feedback: The food was cold and the seat was very cramped.
Label:
"""

response = classifier(prompt, max_new_tokens=10, do_sample=False)
print("Few-shot Classification:", response[0]['generated_text'])

config.json: 0.00B [00:00, ?B/s]

c:\Users\ASUS\miniconda3\envs\aai_gpu_env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub\models--google--flan-t5-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Device set to use cpu

Few-shot Classification: dissatisfied